### ISSUE TITLE
> :last-child does not apply to descendants

### ISSUE THREAD

**Issue by chharvey** [inuitcss/objects.box#5]
I assume the `> :last-child` selector on [Line 37](https://github.com/inuitcss/objects.box/blob/master/_objects.box.scss#L37) is there so that the margin-bottom on the last child and the padding-bottom on the Box do not add to create too much bottom space. But what if the last child has a child element, and _that_ element has a margin-bottom?

``` html
<section class="o-Box">
    <p> this p has a margin-bottom of, say, 24px </p>
    <p> another margin-bottom of 24px </p>
    <footer>
        this footer has no margin-bottom because it is selected by .o-Box > :last-child
        <p>
            this p has a margin-bottom of 24px, but it should not!
            this p's margin-bottom will add to the o-Box's padding-bottom.
        </p>
    </footer>
</section>
```

I would propose changing the selector from `> :last-child {}` to `:last-child {}` (from child selector to descendant selector), but that would not be correct because it would select _all_ last-children inside the Box; it would not select only the last children of the last children elements. Ideally, it would be an arbitrary chain of child selectors, albeit impossible to do:

``` css
    > :last-child,
    > :last-child > :last-child,
    > :last-child > :last-child > :last-child, ... {
        margin-bottom: 0;
    }
```

**Comment by nenadjelovac** [comment]
I usually use something like this:

``` scss
p:not(:last-child) {
    margin-bottom: <value>;
}
```

which effectively works around the issue. But I think you are right, there should be a fix for usecase you provided above. As for the proposed solution, I wouldn't go more than three levels deep, though. 

Let's see what @csswizardry has to say about this.

**Comment by csswizardry** [comment]
I think this would be baking way-too-specific information into the framework. I want to catch 90% of cases and have the implementors handle the 10% themselves :)

**Comment by csshugs** [comment]
@chharvey 

This would solve your problem as well, without adding extra lines of css:

``` html
<section class="o-Box">
    <p> this p has a margin-bottom of, say, 24px </p>
    <p> another margin-bottom of 24px </p>
    <footer>
        this footer has no margin-bottom because it is selected by .o-Box > :last-child
        <p class="u-mb0">
            this p has a margin-bottom of 24px, but it should not!
            this p's margin-bottom will add to the o-Box's padding-bottom.
        </p>
    </footer>
</section>
```

...presuming you got the [inuit-spacings](https://github.com/inuitcss/trumps.spacing) enabled.

**Comment by nenadjelovac** [comment]
@csswizardry 

>  I want to catch 90% of cases and have the **implementors handle the 10% themselves :)**

Makes sense :)

@csshugs 

> ...presuming you got the inuit-spacings enabled.

yes, and presuming you have access to html (eg. it's not CMS generated html/content).

**Comment by chharvey** [comment]
Just came across these articles… Looks like I wasn't the first to discover this problem.

https://css-tricks.com/spacing-the-bottom-of-modules/

http://alistapart.com/article/axiomatic-css-and-lobotomized-owls
