### ISSUE TITLE
Replacement for .island?

### ISSUE THREAD

**Issue by SevenZark** [inuitcss/objects.box#7]
I worked with the previous version of inuit, under csswizardy. There was an object, 'island', which was used extensively in a project I had worked on. I wanted to use it in a new project but I don't see it in this new version anywhere.

Is .box a philosophical inheritor from the .island idea? If not, is there some new technique or way of achieving the same effect in the new version?

**Comment by florianbouvot** [comment]
Yes `box` correspond `island` in inuit v5.

**Comment by SevenZark** [comment]
Great, thanks for the clarification!
